language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# run tests
jobs:
  include:
    - stage: test
      python: '2.7'
      script:
        - python -m pytest -v tests/tests_cli.py --impl=docopt_cli
    - stage: test
      python: '3.4'
      script:
        - python -m pytest -v tests/tests_cli.py --impl=docopt_cli
    - stage: test
      python: '3.5'
      script:
        - python -m pytest -v tests/tests_cli.py --impl=docopt_cli
    - stage: test
      python: '3.6'
      script:
        - python -m pytest -v tests/tests_cli.py --impl=docopt_cli
    - stage: test
      python: '3.7'
      dist: xenial
      script:
        - python -m pytest -v tests/tests_cli.py --impl=docopt_cli
# generate code coverage report
#after_success:
#  - codecov
